theme: jekyll-theme-tactile
version:     "001--10-Feb-2022"
copyright:   "2022"
author:      "raissa thahira"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/raissathahira/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
